### ISSUE TITLE
A03 All: Request History

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#9] opened 2024-10-23 12:27 UTC
**Description**
Allow a user and admin to see the requests history. 

**Business rules:**
user = restricted view to their own request history
admin = no restrictions - show all user requests on the platform.

**Transaction storage and tracking**
https://github.com/bitcoin-sv/bsv-faucet/issues/17
It should be a similar structure to the wallet treasury, the wallet treasury will need to be updated and also referenced in a users/transactions tbale. 

Store all transactions in the database with the following details:

Date of Transaction: Record the date and time of each transaction.
TXID: Store the transaction ID for unique identification.
Raw Transaction (Raw TX): Save the raw transaction data.
Beef Transaction (Beef TX): Include parsed transaction details for further analysis.
Vout (Output Tracking) - Track outputs to determine whether they are spendable or not.
Transaction Type (TX Type): Define the type of transaction (e.g., incoming, outgoing).
Spent Status: - Initially set to false when a transaction is received. Mark the transaction as Spent (true) or Unspent (false). Update to true when the transaction has been used or sent to a user.
Testnet Flag: - Set a flag indicating the transaction is on the testnet (true).
Amount (in Satoshis): Record the transaction amount in satoshis for precision.

**Acceptance Criteria:**
0. Ensure the database schema structure is created and migration scripts run. 
1. I can access the full history" tab from /requests page.
2. I can access the most recent 5 requests preview from the /dashboard page.
2. The transaction history includes all incoming and outgoing transactions related to my own activity (user role = 1) and all activity (admin role = 2)
3. Each transaction entry displays:
    - Date and time of the transaction
    - Txid
    - Account _(visible for admin only)_
    - Beef Transaction (Beef TX)
    - Transaction type (incoming/outgoing)
    - Amount of BSV tokens 
    - Status (e.g., pending, confirmed, failed)
4. Clicking the line item will take me directly to the blockexplorer transaction ID. ([test.whatsonchain.com](http://test.whatsonchain.com/))
5. The system updates the transaction history in real-time reflecting the latest request activity
6. I can export my complete transaction history as a CSV file for offline review and record-keeping.

**Comment by od-hunter** [comment] 2024-10-23 14:31
hi @mo-jaber , can i be assigned this when od hack starts? I'm ready to work.
Here is my [ profile](https://app.onlydust.com/u/od-hunter)

**Comment by CollinsC1O** [comment] 2024-10-24 07:28
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and will love to work on this issue. Please assign

**Comment by martinvibes** [comment] 2024-10-24 07:34
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer i would love to work on this issue 
Pleasee kindly assign :)

**Comment by Oshioke-Salaki** [comment] 2024-10-24 07:37
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a frontend developer with alot of flexibility. I have worked on projects in several ecosystems. from webapplications, to contracts and to dapps. Therefore i believe that i am equipped to handle this issue and contribute to this ecosystem.

### How I plan on tackling this issue
I would take a look at the requirments and follow it exactly to make sure that i complete everything and leave no stone unturned. I would first go through the codebase to understand the project and coding styles.

**Comment by saimeunt** [comment] 2024-10-24 08:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I'm the maintainer of op-scan (https://github.com/walnuthq/op-scan) a blockchain explorer with a very similar tech stack so I'm familiar with the patterns and best practices used in this project. I will use my XP in Full Stack Web3 Development to implement this issue.

### How I plan on tackling this issue
The user story being self explanatory, I will carefully implement it using the latest Next.js best practices, choosing the right shadcn/ui component for the job. I will probably use a Data Table to let the admin filter/sort the entire request history. I will use an API route to get the data in CSV.

**Comment by Benjtalkshow** [comment] 2024-10-24 08:32
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will implement a comprehensive Request History feature that allows both users and admins to view transaction requests. Users will have restricted access to view only their own request history, while admins will be able to see all requests on the platform without any restrictions.

On the `/requests page`, I will provide a full history tab where users can access their transaction history. From the `/dashboard page`, users will see a preview of their most recent five requests for quick reference. The transaction history will include all incoming and outgoing transactions related to their activities (for users) and all activities across the platform (for admins).

Each transaction entry will display crucial information such as the date and time of the transaction, transaction ID (Txid), account (visible only to admins), transaction type (incoming or outgoing), amount of BSV tokens, and the status (pending, confirmed, or failed). Clicking on any line item will redirect users to the transaction ID on the block explorer at test.whatsonchain.com.

I will ensure that the transaction history updates in real-time to reflect the latest request activity, providing users and admins with the most current information. Also, users will have the option to export their complete transaction history as a CSV file for offline review and record-keeping, enhancing their ability to track their activities on the platform.

**Comment by ShantelPeters** [comment] 2024-10-24 09:57
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
 have a solid background in full-stack web development, with experience in building user management systems and implementing role-based access controls. This experience equips me to effectively design and implement the requests history feature, ensuring that the system adheres to the specified business rules while maintaining a seamless user experience.

### How I plan on tackling this issue
To implement the request history feature, I will begin by designing the user interface for both user and admin roles to ensure intuitive access to the transaction history. For users, I will restrict views to their own request history while allowing admins to view all user requests. I will set up a dedicated tab on the /requests page and incorporate a preview of the five most recent requests on the /dashboard page.

Next, I will implement backend functionality to retrieve and display transaction details, including the date and time, transaction ID, account (admin only), transaction type, amount of BSV tokens, and status. I will ensure that clicking on a transaction entry redirects users to the appropriate block explorer link. 

To facilitate real-time updates, I will utilize WebSocket or similar technology to refresh the transaction history dynamically. Additionally, I will incorporate an export feature, enabling users to download their complete transaction history as a CSV file for offline record-keeping. Throughout the development process, I will prioritize security and data integrity to protect user information and transaction details.

**Comment by mo-jaber** [comment] 2024-10-30 09:21
re-assigned to @saimeunt

**Comment by mo-jaber** [comment] 2024-11-02 14:05
@saimeunt how are you going?

**Comment by od-hunter** [comment] 2024-11-03 12:28
> @saimeunt how are you going?

If the assigned is not working on it, please can I work on this? I’m ready to work on it asap.

**Comment by saimeunt** [comment] 2024-11-03 12:38
@od-hunter @mo-jaber Working on it atm!

**Closed** 2024-11-04 13:03 UTC
Labels: ODHack9, dep #17
